create table SampleSB_SampleSB (
	uuid_ VARCHAR(75) null,
	samplesbId LONG not null primary key,
	title VARCHAR(75) null,
	startDate DATE null,
	endDate DATE null,
	samplesbBooleanStat BOOLEAN,
	samplesbDateTime DATE null,
	samplesbDocument LONG,
	folderDLId LONG,
	samplesbDocumentLibrary VARCHAR(512) null,
	samplesbDouble DOUBLE,
	samplesbInteger INTEGER,
	samplesbRichText TEXT null,
	samplesbText TEXT null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	urlTitle VARCHAR(75) null,
	samplesbTitleName VARCHAR(255) null,
	samplesbSummaryName TEXT null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);