/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.test.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import com.liferay.test.model.SampleSB;
import com.liferay.test.model.SampleSBModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the SampleSB service. Represents a row in the &quot;SampleSB_SampleSB&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link SampleSBModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SampleSBImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SampleSBImpl
 * @see SampleSB
 * @see SampleSBModel
 * @generated
 */
@ProviderType
public class SampleSBModelImpl extends BaseModelImpl<SampleSB>
	implements SampleSBModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sample sb model instance should use the {@link SampleSB} interface instead.
	 */
	public static final String TABLE_NAME = "SampleSB_SampleSB";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "samplesbId", Types.BIGINT },
			{ "title", Types.VARCHAR },
			{ "startDate", Types.TIMESTAMP },
			{ "endDate", Types.TIMESTAMP },
			{ "samplesbBooleanStat", Types.BOOLEAN },
			{ "samplesbDateTime", Types.TIMESTAMP },
			{ "samplesbDocument", Types.BIGINT },
			{ "folderDLId", Types.BIGINT },
			{ "samplesbDocumentLibrary", Types.VARCHAR },
			{ "samplesbDouble", Types.DOUBLE },
			{ "samplesbInteger", Types.INTEGER },
			{ "samplesbRichText", Types.VARCHAR },
			{ "samplesbText", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "urlTitle", Types.VARCHAR },
			{ "samplesbTitleName", Types.VARCHAR },
			{ "samplesbSummaryName", Types.VARCHAR },
			{ "status", Types.INTEGER },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("samplesbId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("samplesbBooleanStat", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("samplesbDateTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("samplesbDocument", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("folderDLId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("samplesbDocumentLibrary", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("samplesbDouble", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("samplesbInteger", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("samplesbRichText", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("samplesbText", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("urlTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("samplesbTitleName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("samplesbSummaryName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table SampleSB_SampleSB (uuid_ VARCHAR(75) null,samplesbId LONG not null primary key,title VARCHAR(75) null,startDate DATE null,endDate DATE null,samplesbBooleanStat BOOLEAN,samplesbDateTime DATE null,samplesbDocument LONG,folderDLId LONG,samplesbDocumentLibrary VARCHAR(75) null,samplesbDouble DOUBLE,samplesbInteger INTEGER,samplesbRichText VARCHAR(75) null,samplesbText VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,urlTitle VARCHAR(75) null,samplesbTitleName VARCHAR(75) null,samplesbSummaryName VARCHAR(75) null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table SampleSB_SampleSB";
	public static final String ORDER_BY_JPQL = " ORDER BY sampleSB.samplesbId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SampleSB_SampleSB.samplesbId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.test.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.test.model.SampleSB"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.test.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.test.model.SampleSB"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.test.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.test.model.SampleSB"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long ENDDATE_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long SAMPLESBBOOLEANSTAT_COLUMN_BITMASK = 8L;
	public static final long SAMPLESBDATETIME_COLUMN_BITMASK = 16L;
	public static final long SAMPLESBDOCUMENT_COLUMN_BITMASK = 32L;
	public static final long SAMPLESBDOCUMENTLIBRARY_COLUMN_BITMASK = 64L;
	public static final long SAMPLESBDOUBLE_COLUMN_BITMASK = 128L;
	public static final long SAMPLESBID_COLUMN_BITMASK = 256L;
	public static final long SAMPLESBINTEGER_COLUMN_BITMASK = 512L;
	public static final long SAMPLESBRICHTEXT_COLUMN_BITMASK = 1024L;
	public static final long SAMPLESBTEXT_COLUMN_BITMASK = 2048L;
	public static final long STARTDATE_COLUMN_BITMASK = 4096L;
	public static final long STATUS_COLUMN_BITMASK = 8192L;
	public static final long TITLE_COLUMN_BITMASK = 16384L;
	public static final long URLTITLE_COLUMN_BITMASK = 32768L;
	public static final long USERID_COLUMN_BITMASK = 65536L;
	public static final long UUID_COLUMN_BITMASK = 131072L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.test.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.test.model.SampleSB"));

	public SampleSBModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _samplesbId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSamplesbId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _samplesbId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SampleSB.class;
	}

	@Override
	public String getModelClassName() {
		return SampleSB.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("samplesbId", getSamplesbId());
		attributes.put("title", getTitle());
		attributes.put("startDate", getStartDate());
		attributes.put("endDate", getEndDate());
		attributes.put("samplesbBooleanStat", getSamplesbBooleanStat());
		attributes.put("samplesbDateTime", getSamplesbDateTime());
		attributes.put("samplesbDocument", getSamplesbDocument());
		attributes.put("folderDLId", getFolderDLId());
		attributes.put("samplesbDocumentLibrary", getSamplesbDocumentLibrary());
		attributes.put("samplesbDouble", getSamplesbDouble());
		attributes.put("samplesbInteger", getSamplesbInteger());
		attributes.put("samplesbRichText", getSamplesbRichText());
		attributes.put("samplesbText", getSamplesbText());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("urlTitle", getUrlTitle());
		attributes.put("samplesbTitleName", getSamplesbTitleName());
		attributes.put("samplesbSummaryName", getSamplesbSummaryName());
		attributes.put("status", getStatus());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusDate", getStatusDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long samplesbId = (Long)attributes.get("samplesbId");

		if (samplesbId != null) {
			setSamplesbId(samplesbId);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		Date startDate = (Date)attributes.get("startDate");

		if (startDate != null) {
			setStartDate(startDate);
		}

		Date endDate = (Date)attributes.get("endDate");

		if (endDate != null) {
			setEndDate(endDate);
		}

		Boolean samplesbBooleanStat = (Boolean)attributes.get(
				"samplesbBooleanStat");

		if (samplesbBooleanStat != null) {
			setSamplesbBooleanStat(samplesbBooleanStat);
		}

		Date samplesbDateTime = (Date)attributes.get("samplesbDateTime");

		if (samplesbDateTime != null) {
			setSamplesbDateTime(samplesbDateTime);
		}

		Long samplesbDocument = (Long)attributes.get("samplesbDocument");

		if (samplesbDocument != null) {
			setSamplesbDocument(samplesbDocument);
		}

		Long folderDLId = (Long)attributes.get("folderDLId");

		if (folderDLId != null) {
			setFolderDLId(folderDLId);
		}

		String samplesbDocumentLibrary = (String)attributes.get(
				"samplesbDocumentLibrary");

		if (samplesbDocumentLibrary != null) {
			setSamplesbDocumentLibrary(samplesbDocumentLibrary);
		}

		Double samplesbDouble = (Double)attributes.get("samplesbDouble");

		if (samplesbDouble != null) {
			setSamplesbDouble(samplesbDouble);
		}

		Integer samplesbInteger = (Integer)attributes.get("samplesbInteger");

		if (samplesbInteger != null) {
			setSamplesbInteger(samplesbInteger);
		}

		String samplesbRichText = (String)attributes.get("samplesbRichText");

		if (samplesbRichText != null) {
			setSamplesbRichText(samplesbRichText);
		}

		String samplesbText = (String)attributes.get("samplesbText");

		if (samplesbText != null) {
			setSamplesbText(samplesbText);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String urlTitle = (String)attributes.get("urlTitle");

		if (urlTitle != null) {
			setUrlTitle(urlTitle);
		}

		String samplesbTitleName = (String)attributes.get("samplesbTitleName");

		if (samplesbTitleName != null) {
			setSamplesbTitleName(samplesbTitleName);
		}

		String samplesbSummaryName = (String)attributes.get(
				"samplesbSummaryName");

		if (samplesbSummaryName != null) {
			setSamplesbSummaryName(samplesbSummaryName);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusDate = (Date)attributes.get("statusDate");

		if (statusDate != null) {
			setStatusDate(statusDate);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getSamplesbId() {
		return _samplesbId;
	}

	@Override
	public void setSamplesbId(long samplesbId) {
		_columnBitmask |= SAMPLESBID_COLUMN_BITMASK;

		if (!_setOriginalSamplesbId) {
			_setOriginalSamplesbId = true;

			_originalSamplesbId = _samplesbId;
		}

		_samplesbId = samplesbId;
	}

	public long getOriginalSamplesbId() {
		return _originalSamplesbId;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_columnBitmask |= TITLE_COLUMN_BITMASK;

		if (_originalTitle == null) {
			_originalTitle = _title;
		}

		_title = title;
	}

	public String getOriginalTitle() {
		return GetterUtil.getString(_originalTitle);
	}

	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_columnBitmask |= STARTDATE_COLUMN_BITMASK;

		if (_originalStartDate == null) {
			_originalStartDate = _startDate;
		}

		_startDate = startDate;
	}

	public Date getOriginalStartDate() {
		return _originalStartDate;
	}

	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		_columnBitmask |= ENDDATE_COLUMN_BITMASK;

		if (_originalEndDate == null) {
			_originalEndDate = _endDate;
		}

		_endDate = endDate;
	}

	public Date getOriginalEndDate() {
		return _originalEndDate;
	}

	@Override
	public boolean getSamplesbBooleanStat() {
		return _samplesbBooleanStat;
	}

	@Override
	public boolean isSamplesbBooleanStat() {
		return _samplesbBooleanStat;
	}

	@Override
	public void setSamplesbBooleanStat(boolean samplesbBooleanStat) {
		_columnBitmask |= SAMPLESBBOOLEANSTAT_COLUMN_BITMASK;

		if (!_setOriginalSamplesbBooleanStat) {
			_setOriginalSamplesbBooleanStat = true;

			_originalSamplesbBooleanStat = _samplesbBooleanStat;
		}

		_samplesbBooleanStat = samplesbBooleanStat;
	}

	public boolean getOriginalSamplesbBooleanStat() {
		return _originalSamplesbBooleanStat;
	}

	@Override
	public Date getSamplesbDateTime() {
		return _samplesbDateTime;
	}

	@Override
	public void setSamplesbDateTime(Date samplesbDateTime) {
		_columnBitmask |= SAMPLESBDATETIME_COLUMN_BITMASK;

		if (_originalSamplesbDateTime == null) {
			_originalSamplesbDateTime = _samplesbDateTime;
		}

		_samplesbDateTime = samplesbDateTime;
	}

	public Date getOriginalSamplesbDateTime() {
		return _originalSamplesbDateTime;
	}

	@Override
	public long getSamplesbDocument() {
		return _samplesbDocument;
	}

	@Override
	public void setSamplesbDocument(long samplesbDocument) {
		_columnBitmask |= SAMPLESBDOCUMENT_COLUMN_BITMASK;

		if (!_setOriginalSamplesbDocument) {
			_setOriginalSamplesbDocument = true;

			_originalSamplesbDocument = _samplesbDocument;
		}

		_samplesbDocument = samplesbDocument;
	}

	public long getOriginalSamplesbDocument() {
		return _originalSamplesbDocument;
	}

	@Override
	public long getFolderDLId() {
		return _folderDLId;
	}

	@Override
	public void setFolderDLId(long folderDLId) {
		_folderDLId = folderDLId;
	}

	@Override
	public String getSamplesbDocumentLibrary() {
		if (_samplesbDocumentLibrary == null) {
			return StringPool.BLANK;
		}
		else {
			return _samplesbDocumentLibrary;
		}
	}

	@Override
	public void setSamplesbDocumentLibrary(String samplesbDocumentLibrary) {
		_columnBitmask |= SAMPLESBDOCUMENTLIBRARY_COLUMN_BITMASK;

		if (_originalSamplesbDocumentLibrary == null) {
			_originalSamplesbDocumentLibrary = _samplesbDocumentLibrary;
		}

		_samplesbDocumentLibrary = samplesbDocumentLibrary;
	}

	public String getOriginalSamplesbDocumentLibrary() {
		return GetterUtil.getString(_originalSamplesbDocumentLibrary);
	}

	@Override
	public double getSamplesbDouble() {
		return _samplesbDouble;
	}

	@Override
	public void setSamplesbDouble(double samplesbDouble) {
		_columnBitmask |= SAMPLESBDOUBLE_COLUMN_BITMASK;

		if (!_setOriginalSamplesbDouble) {
			_setOriginalSamplesbDouble = true;

			_originalSamplesbDouble = _samplesbDouble;
		}

		_samplesbDouble = samplesbDouble;
	}

	public double getOriginalSamplesbDouble() {
		return _originalSamplesbDouble;
	}

	@Override
	public int getSamplesbInteger() {
		return _samplesbInteger;
	}

	@Override
	public void setSamplesbInteger(int samplesbInteger) {
		_columnBitmask |= SAMPLESBINTEGER_COLUMN_BITMASK;

		if (!_setOriginalSamplesbInteger) {
			_setOriginalSamplesbInteger = true;

			_originalSamplesbInteger = _samplesbInteger;
		}

		_samplesbInteger = samplesbInteger;
	}

	public int getOriginalSamplesbInteger() {
		return _originalSamplesbInteger;
	}

	@Override
	public String getSamplesbRichText() {
		if (_samplesbRichText == null) {
			return StringPool.BLANK;
		}
		else {
			return _samplesbRichText;
		}
	}

	@Override
	public void setSamplesbRichText(String samplesbRichText) {
		_columnBitmask |= SAMPLESBRICHTEXT_COLUMN_BITMASK;

		if (_originalSamplesbRichText == null) {
			_originalSamplesbRichText = _samplesbRichText;
		}

		_samplesbRichText = samplesbRichText;
	}

	public String getOriginalSamplesbRichText() {
		return GetterUtil.getString(_originalSamplesbRichText);
	}

	@Override
	public String getSamplesbText() {
		if (_samplesbText == null) {
			return StringPool.BLANK;
		}
		else {
			return _samplesbText;
		}
	}

	@Override
	public void setSamplesbText(String samplesbText) {
		_columnBitmask |= SAMPLESBTEXT_COLUMN_BITMASK;

		if (_originalSamplesbText == null) {
			_originalSamplesbText = _samplesbText;
		}

		_samplesbText = samplesbText;
	}

	public String getOriginalSamplesbText() {
		return GetterUtil.getString(_originalSamplesbText);
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getUrlTitle() {
		if (_urlTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _urlTitle;
		}
	}

	@Override
	public void setUrlTitle(String urlTitle) {
		_columnBitmask |= URLTITLE_COLUMN_BITMASK;

		if (_originalUrlTitle == null) {
			_originalUrlTitle = _urlTitle;
		}

		_urlTitle = urlTitle;
	}

	public String getOriginalUrlTitle() {
		return GetterUtil.getString(_originalUrlTitle);
	}

	@Override
	public String getSamplesbTitleName() {
		if (_samplesbTitleName == null) {
			return StringPool.BLANK;
		}
		else {
			return _samplesbTitleName;
		}
	}

	@Override
	public void setSamplesbTitleName(String samplesbTitleName) {
		_samplesbTitleName = samplesbTitleName;
	}

	@Override
	public String getSamplesbSummaryName() {
		if (_samplesbSummaryName == null) {
			return StringPool.BLANK;
		}
		else {
			return _samplesbSummaryName;
		}
	}

	@Override
	public void setSamplesbSummaryName(String samplesbSummaryName) {
		_samplesbSummaryName = samplesbSummaryName;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				SampleSB.class.getName()));
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {
		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry = com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.fetchEntry(getModelClassName(),
				getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler = getTrashHandler();

		if (!Validator.isNull(trashHandler.getContainerModelClassName(
						getPrimaryKey()))) {
			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException nsme) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler = com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.getTrashHandler(trashHandler.getContainerModelClassName(
							containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	* @deprecated As of 7.0.0, with no direct replacement
	*/
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler = getTrashHandler();

		if ((trashHandler == null) ||
				Validator.isNull(trashHandler.getContainerModelClassName(
						getPrimaryKey()))) {
			return false;
		}

		try {
			ContainerModel containerModel = trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception e) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry = com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.fetchEntry(getModelClassName(),
				getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry = com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.fetchEntry(getModelClassName(),
				getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			SampleSB.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SampleSB toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SampleSB)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SampleSBImpl sampleSBImpl = new SampleSBImpl();

		sampleSBImpl.setUuid(getUuid());
		sampleSBImpl.setSamplesbId(getSamplesbId());
		sampleSBImpl.setTitle(getTitle());
		sampleSBImpl.setStartDate(getStartDate());
		sampleSBImpl.setEndDate(getEndDate());
		sampleSBImpl.setSamplesbBooleanStat(getSamplesbBooleanStat());
		sampleSBImpl.setSamplesbDateTime(getSamplesbDateTime());
		sampleSBImpl.setSamplesbDocument(getSamplesbDocument());
		sampleSBImpl.setFolderDLId(getFolderDLId());
		sampleSBImpl.setSamplesbDocumentLibrary(getSamplesbDocumentLibrary());
		sampleSBImpl.setSamplesbDouble(getSamplesbDouble());
		sampleSBImpl.setSamplesbInteger(getSamplesbInteger());
		sampleSBImpl.setSamplesbRichText(getSamplesbRichText());
		sampleSBImpl.setSamplesbText(getSamplesbText());
		sampleSBImpl.setGroupId(getGroupId());
		sampleSBImpl.setCompanyId(getCompanyId());
		sampleSBImpl.setUserId(getUserId());
		sampleSBImpl.setUserName(getUserName());
		sampleSBImpl.setCreateDate(getCreateDate());
		sampleSBImpl.setModifiedDate(getModifiedDate());
		sampleSBImpl.setUrlTitle(getUrlTitle());
		sampleSBImpl.setSamplesbTitleName(getSamplesbTitleName());
		sampleSBImpl.setSamplesbSummaryName(getSamplesbSummaryName());
		sampleSBImpl.setStatus(getStatus());
		sampleSBImpl.setStatusByUserId(getStatusByUserId());
		sampleSBImpl.setStatusByUserName(getStatusByUserName());
		sampleSBImpl.setStatusDate(getStatusDate());

		sampleSBImpl.resetOriginalValues();

		return sampleSBImpl;
	}

	@Override
	public int compareTo(SampleSB sampleSB) {
		long primaryKey = sampleSB.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SampleSB)) {
			return false;
		}

		SampleSB sampleSB = (SampleSB)obj;

		long primaryKey = sampleSB.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		SampleSBModelImpl sampleSBModelImpl = this;

		sampleSBModelImpl._originalUuid = sampleSBModelImpl._uuid;

		sampleSBModelImpl._originalSamplesbId = sampleSBModelImpl._samplesbId;

		sampleSBModelImpl._setOriginalSamplesbId = false;

		sampleSBModelImpl._originalTitle = sampleSBModelImpl._title;

		sampleSBModelImpl._originalStartDate = sampleSBModelImpl._startDate;

		sampleSBModelImpl._originalEndDate = sampleSBModelImpl._endDate;

		sampleSBModelImpl._originalSamplesbBooleanStat = sampleSBModelImpl._samplesbBooleanStat;

		sampleSBModelImpl._setOriginalSamplesbBooleanStat = false;

		sampleSBModelImpl._originalSamplesbDateTime = sampleSBModelImpl._samplesbDateTime;

		sampleSBModelImpl._originalSamplesbDocument = sampleSBModelImpl._samplesbDocument;

		sampleSBModelImpl._setOriginalSamplesbDocument = false;

		sampleSBModelImpl._originalSamplesbDocumentLibrary = sampleSBModelImpl._samplesbDocumentLibrary;

		sampleSBModelImpl._originalSamplesbDouble = sampleSBModelImpl._samplesbDouble;

		sampleSBModelImpl._setOriginalSamplesbDouble = false;

		sampleSBModelImpl._originalSamplesbInteger = sampleSBModelImpl._samplesbInteger;

		sampleSBModelImpl._setOriginalSamplesbInteger = false;

		sampleSBModelImpl._originalSamplesbRichText = sampleSBModelImpl._samplesbRichText;

		sampleSBModelImpl._originalSamplesbText = sampleSBModelImpl._samplesbText;

		sampleSBModelImpl._originalGroupId = sampleSBModelImpl._groupId;

		sampleSBModelImpl._setOriginalGroupId = false;

		sampleSBModelImpl._originalCompanyId = sampleSBModelImpl._companyId;

		sampleSBModelImpl._setOriginalCompanyId = false;

		sampleSBModelImpl._originalUserId = sampleSBModelImpl._userId;

		sampleSBModelImpl._setOriginalUserId = false;

		sampleSBModelImpl._setModifiedDate = false;

		sampleSBModelImpl._originalUrlTitle = sampleSBModelImpl._urlTitle;

		sampleSBModelImpl._originalStatus = sampleSBModelImpl._status;

		sampleSBModelImpl._setOriginalStatus = false;

		sampleSBModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SampleSB> toCacheModel() {
		SampleSBCacheModel sampleSBCacheModel = new SampleSBCacheModel();

		sampleSBCacheModel.uuid = getUuid();

		String uuid = sampleSBCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			sampleSBCacheModel.uuid = null;
		}

		sampleSBCacheModel.samplesbId = getSamplesbId();

		sampleSBCacheModel.title = getTitle();

		String title = sampleSBCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			sampleSBCacheModel.title = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			sampleSBCacheModel.startDate = startDate.getTime();
		}
		else {
			sampleSBCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			sampleSBCacheModel.endDate = endDate.getTime();
		}
		else {
			sampleSBCacheModel.endDate = Long.MIN_VALUE;
		}

		sampleSBCacheModel.samplesbBooleanStat = getSamplesbBooleanStat();

		Date samplesbDateTime = getSamplesbDateTime();

		if (samplesbDateTime != null) {
			sampleSBCacheModel.samplesbDateTime = samplesbDateTime.getTime();
		}
		else {
			sampleSBCacheModel.samplesbDateTime = Long.MIN_VALUE;
		}

		sampleSBCacheModel.samplesbDocument = getSamplesbDocument();

		sampleSBCacheModel.folderDLId = getFolderDLId();

		sampleSBCacheModel.samplesbDocumentLibrary = getSamplesbDocumentLibrary();

		String samplesbDocumentLibrary = sampleSBCacheModel.samplesbDocumentLibrary;

		if ((samplesbDocumentLibrary != null) &&
				(samplesbDocumentLibrary.length() == 0)) {
			sampleSBCacheModel.samplesbDocumentLibrary = null;
		}

		sampleSBCacheModel.samplesbDouble = getSamplesbDouble();

		sampleSBCacheModel.samplesbInteger = getSamplesbInteger();

		sampleSBCacheModel.samplesbRichText = getSamplesbRichText();

		String samplesbRichText = sampleSBCacheModel.samplesbRichText;

		if ((samplesbRichText != null) && (samplesbRichText.length() == 0)) {
			sampleSBCacheModel.samplesbRichText = null;
		}

		sampleSBCacheModel.samplesbText = getSamplesbText();

		String samplesbText = sampleSBCacheModel.samplesbText;

		if ((samplesbText != null) && (samplesbText.length() == 0)) {
			sampleSBCacheModel.samplesbText = null;
		}

		sampleSBCacheModel.groupId = getGroupId();

		sampleSBCacheModel.companyId = getCompanyId();

		sampleSBCacheModel.userId = getUserId();

		sampleSBCacheModel.userName = getUserName();

		String userName = sampleSBCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			sampleSBCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			sampleSBCacheModel.createDate = createDate.getTime();
		}
		else {
			sampleSBCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			sampleSBCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			sampleSBCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		sampleSBCacheModel.urlTitle = getUrlTitle();

		String urlTitle = sampleSBCacheModel.urlTitle;

		if ((urlTitle != null) && (urlTitle.length() == 0)) {
			sampleSBCacheModel.urlTitle = null;
		}

		sampleSBCacheModel.samplesbTitleName = getSamplesbTitleName();

		String samplesbTitleName = sampleSBCacheModel.samplesbTitleName;

		if ((samplesbTitleName != null) && (samplesbTitleName.length() == 0)) {
			sampleSBCacheModel.samplesbTitleName = null;
		}

		sampleSBCacheModel.samplesbSummaryName = getSamplesbSummaryName();

		String samplesbSummaryName = sampleSBCacheModel.samplesbSummaryName;

		if ((samplesbSummaryName != null) &&
				(samplesbSummaryName.length() == 0)) {
			sampleSBCacheModel.samplesbSummaryName = null;
		}

		sampleSBCacheModel.status = getStatus();

		sampleSBCacheModel.statusByUserId = getStatusByUserId();

		sampleSBCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = sampleSBCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			sampleSBCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			sampleSBCacheModel.statusDate = statusDate.getTime();
		}
		else {
			sampleSBCacheModel.statusDate = Long.MIN_VALUE;
		}

		return sampleSBCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(55);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", samplesbId=");
		sb.append(getSamplesbId());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", startDate=");
		sb.append(getStartDate());
		sb.append(", endDate=");
		sb.append(getEndDate());
		sb.append(", samplesbBooleanStat=");
		sb.append(getSamplesbBooleanStat());
		sb.append(", samplesbDateTime=");
		sb.append(getSamplesbDateTime());
		sb.append(", samplesbDocument=");
		sb.append(getSamplesbDocument());
		sb.append(", folderDLId=");
		sb.append(getFolderDLId());
		sb.append(", samplesbDocumentLibrary=");
		sb.append(getSamplesbDocumentLibrary());
		sb.append(", samplesbDouble=");
		sb.append(getSamplesbDouble());
		sb.append(", samplesbInteger=");
		sb.append(getSamplesbInteger());
		sb.append(", samplesbRichText=");
		sb.append(getSamplesbRichText());
		sb.append(", samplesbText=");
		sb.append(getSamplesbText());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", urlTitle=");
		sb.append(getUrlTitle());
		sb.append(", samplesbTitleName=");
		sb.append(getSamplesbTitleName());
		sb.append(", samplesbSummaryName=");
		sb.append(getSamplesbSummaryName());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusDate=");
		sb.append(getStatusDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(85);

		sb.append("<model><model-name>");
		sb.append("com.liferay.test.model.SampleSB");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>samplesbId</column-name><column-value><![CDATA[");
		sb.append(getSamplesbId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startDate</column-name><column-value><![CDATA[");
		sb.append(getStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endDate</column-name><column-value><![CDATA[");
		sb.append(getEndDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>samplesbBooleanStat</column-name><column-value><![CDATA[");
		sb.append(getSamplesbBooleanStat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>samplesbDateTime</column-name><column-value><![CDATA[");
		sb.append(getSamplesbDateTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>samplesbDocument</column-name><column-value><![CDATA[");
		sb.append(getSamplesbDocument());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>folderDLId</column-name><column-value><![CDATA[");
		sb.append(getFolderDLId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>samplesbDocumentLibrary</column-name><column-value><![CDATA[");
		sb.append(getSamplesbDocumentLibrary());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>samplesbDouble</column-name><column-value><![CDATA[");
		sb.append(getSamplesbDouble());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>samplesbInteger</column-name><column-value><![CDATA[");
		sb.append(getSamplesbInteger());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>samplesbRichText</column-name><column-value><![CDATA[");
		sb.append(getSamplesbRichText());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>samplesbText</column-name><column-value><![CDATA[");
		sb.append(getSamplesbText());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>urlTitle</column-name><column-value><![CDATA[");
		sb.append(getUrlTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>samplesbTitleName</column-name><column-value><![CDATA[");
		sb.append(getSamplesbTitleName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>samplesbSummaryName</column-name><column-value><![CDATA[");
		sb.append(getSamplesbSummaryName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusDate</column-name><column-value><![CDATA[");
		sb.append(getStatusDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = SampleSB.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			SampleSB.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _samplesbId;
	private long _originalSamplesbId;
	private boolean _setOriginalSamplesbId;
	private String _title;
	private String _originalTitle;
	private Date _startDate;
	private Date _originalStartDate;
	private Date _endDate;
	private Date _originalEndDate;
	private boolean _samplesbBooleanStat;
	private boolean _originalSamplesbBooleanStat;
	private boolean _setOriginalSamplesbBooleanStat;
	private Date _samplesbDateTime;
	private Date _originalSamplesbDateTime;
	private long _samplesbDocument;
	private long _originalSamplesbDocument;
	private boolean _setOriginalSamplesbDocument;
	private long _folderDLId;
	private String _samplesbDocumentLibrary;
	private String _originalSamplesbDocumentLibrary;
	private double _samplesbDouble;
	private double _originalSamplesbDouble;
	private boolean _setOriginalSamplesbDouble;
	private int _samplesbInteger;
	private int _originalSamplesbInteger;
	private boolean _setOriginalSamplesbInteger;
	private String _samplesbRichText;
	private String _originalSamplesbRichText;
	private String _samplesbText;
	private String _originalSamplesbText;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _urlTitle;
	private String _originalUrlTitle;
	private String _samplesbTitleName;
	private String _samplesbSummaryName;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _columnBitmask;
	private SampleSB _escapedModel;
}